import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Maximilian's Web3 Security Research",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = (
    <header className="itunes-header h-16 flex-shrink-0">
      <div className="flex justify-between items-center h-full px-4">
        <Link href="/" className="flex items-center">
          <span className="text-lg font-semibold text-gray-800">MaximilianSecurity.xyz</span>
        </Link>
        <Link href="/about">
          <Image
            src="/images/profile.jpg"
            alt="Profile"
            width={40}
            height={40}
            className="rounded-full object-cover border-2 border-gray-300"
          />
        </Link>
      </div>
    </header>
  );

  return (
    <html lang="en">
      <body className="h-screen flex flex-col">
        {header}
        <div className="flex flex-1 overflow-hidden">
          <Sidebar />
          <main className="flex-1 overflow-y-auto bg-gray-50">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
